# Site settings
title: XTargets
email: bradphelan@xtargets.com
description: "XTargets - Technical blog of Brad Phelan"
baseurl: ""
url: "http://xtargets.com"

# Build settings
markdown: redcarpet
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: post
    values:
      layout: post
